name: CI Ubunutu

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v1.3.0
    
    - name: Compile
      run: cargo test --no-run
    
    - name: Test
      run: cargo test --all-features -- --nocapture --quiet
    
    - name: Run Benchmarks
      run: cargo bench --all-features
